server:
  port: 8062

#DataSource Config
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: true  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix: .html
      #encoding: UTF-8
      #content-type: text/html
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.133.215.11:3306/hotel?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: Lgh@159815987

  freemarker:
    suffix: ftl

mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    map-underscore-to-camel-case: false

